# Generated by Django 6.0 on 2026-03-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Zona de Envío',
                'verbose_name_plural': 'Zonas de Envío',
                'ordering': ['name'],
            },
        ),
    ]
